# Generated by Django 4.0.3 on 2022-03-31 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_products_desription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='desription',
            new_name='description',
        ),
    ]
