# Generated by Django 4.0.3 on 2022-04-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_products_price_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
